
#ifndef INNOEXTRACT_CONFIGURE_HPP
#define INNOEXTRACT_CONFIGURE_HPP

// Console functions
#undef INNOEXTRACT_HAVE_ISATTY
#undef INNOEXTRACT_HAVE_MS_ISATTY
#undef INNOEXTRACT_HAVE_IOCTL

// Time functions
#undef INNOEXTRACT_HAVE_MKGMTIME64
#undef INNOEXTRACT_HAVE_TIMEGM
#undef INNOEXTRACT_HAVE_MKGMTIME
#undef INNOEXTRACT_HAVE_GMTIME64_S
#define INNOEXTRACT_HAVE_GMTIME_R true
#undef INNOEXTRACT_HAVE_GMTIME_S

// File functions
#undef INNOEXTRACT_HAVE_UTIMENSAT
#define INNOEXTRACT_HAVE_AT_FDCWD true
#define INNOEXTRACT_HAVE_UTIMES true

// Endianness
#define INNOEXTRACT_HAVE_BSWAP_16 true
#define INNOEXTRACT_HAVE_BSWAP_32 true
#define INNOEXTRACT_HAVE_BSWAP_64 true

// C++11 functionality
#undef INNOEXTRACT_HAVE_ALIGNOF
#define INNOEXTRACT_HAVE_STD_CODECVT_UTF8_UTF16 true
#undef INNOEXTRACT_HAVE_STD_UNIQUE_PTR

#define INNOEXTRACT_HAVE_LZMA 1

#endif // INNOEXTRACT_CONFIGURE_HPP
